### ISSUE TITLE
Option to select docker stack

### ISSUE THREAD

**Issue by edurenye** [iot-salzburg/gpu-jupyter#10]
There should be a parameter for `generate_Dockerfile.sh` to select the docker stack that you with to install.

In my case I want to run 'tensorflow-notebook' instead of 'datascience-notebook', I know tensorflow is added afterwards, but the final image is too big, and I think it shouldn't be to hard to implement this.

**Comment by ChristophSchranz** [comment]
Hi @edurenye ,
there are reasons, why this isn't useful at the moment:
- the GPU stack requires a robust data-science stack, yes, 'scipy' and 'datascience' would fit here.
- the [tensorflow installation](https://github.com/jupyter/docker-stacks/blob/master/tensorflow-notebook/Dockerfile#L10) of the docker-stacks is a one-liner and it is not planed to further improve it. It seems that this repository is an extension for GPU processing.

I think the best option is to fork this repository and modify the installations in `generate_Dockerfile.sh` and the `Dockerfiles`. In `generate_Dockerfile.sh` you can uncomment those installations you won't need, like the R and Julia installation in the 'datascience-notebook'.

I hope my answer helps you!
