### ISSUE TITLE
Building nvtop fails

### ISSUE THREAD

**Issue by ChristofKaufmann** [iot-salzburg/gpu-jupyter#102]
As noticed in #101 the compilation of `nvtop` fails due to missing dependencies. As an alternative, why not using the [ubuntu](https://packages.ubuntu.com/focal/nvtop) version? It could be easily installed through `apt-get`.

**Comment by ChristophSchranz** [comment]
Hi @ChristofKaufmann 
you are right, sorry for not noting this.
I'll put this into the same push as the previous issue you found!
