### ISSUE TITLE
RAPIDSAI - Build Image

### ISSUE THREAD

**Issue by antikilahdjs** [iot-salzburg/gpu-jupyter#105]
Hello everybody. 

Is not a issue or some troubles with this stack but I would like to know if someone can help me to build rapid as singleuser. I tried many times to build but I am not able to build it :(

Somebody have some familiarity with rapids and I can help me ?  Rapids has a image but not works with singleuser as well.

https://rapids.ai/#quick-start

**Comment by mathematicalmichael** [comment]
I have _some_ experience adapting images. If I recall correctly, RAPIDS does have notebook support already so it's a matter of just pulling the right image / adapting it if need be (e.g. for jupyterhub). 

What's the timeline under which you're needing this?
What exactly are you referring to by "singleuser"?
