### ISSUE TITLE
cuda 11.7 version release request

### ISSUE THREAD

**Issue by GeorvityLabs** [iot-salzburg/gpu-jupyter#109]
hey @iot-salzburg,

i hope you release the container for cuda 11.7
i have the 11.6 version, and am currently getting a cuda error since my machine was updated to cuda 11.7
![Screenshot from 2023-04-04 00-10-32](https://user-images.githubusercontent.com/58555432/229706226-a576e658-caeb-407b-a8e7-a1d648c61cd8.png)

**Comment by ChristophSchranz** [comment]
Hi @GeorvityLabs 
 check out the section https://github.com/iot-salzburg/gpu-jupyter#update-cuda-to-another-version for information.
When I made the last update of the stacks, CUDA 11.7 was not supported for all GPU-depended libraries, so I did not update CUDA.

Please let me know if it already works for Tensorflow and PyTorch along the other components and reopen this issue if it is.
