### ISSUE TITLE
nvcc issue

### ISSUE THREAD

**Issue by GeorvityLabs** [iot-salzburg/gpu-jupyter#112]
@iot-salzburg ,

i tried to run nvcc --version from within the notebook , but it shows it isn't there.
any tips on how to fix this issue?

**Comment by steven-hh-ding** [comment]
same - we have to download and install. did it get deleted during the build?

**Comment by ChristophSchranz** [comment]
Hi, 
unfortunately, I can't reproduce this issue. 
nvcc is installed within this lines:
https://github.com/iot-salzburg/gpu-jupyter/blob/5d8443c61663dbcbee6034e9baebd9d61ac6a5c0/src/Dockerfile.gpulibs#L43-L48

Note that this Dockerfile part is stacked together into `.build/Dockerfile`.
The reason why nvcc is installed this way is discussed in https://github.com/iot-salzburg/gpu-jupyter/issues/106.

- Does the error still occur after rebooting?
- What's the output of `nvcc --version` on the host machine?
- Can you manually install the lines and does it work then?
- What image version do you use? Does it also occur with `v1.5_cuda-11.6_ubuntu-20.04`

**Comment by ChristophSchranz** [comment]
Closing as there is no response and the issue seems to not occur anymore on recent versions.
