### ISSUE TITLE
no 'latest' tag on docker hub

### ISSUE THREAD

**Issue by chessman** [iot-salzburg/gpu-jupyter#115]
I noticed that cschranz/gpu-jupyter doesn't have 'latest' tag anymore.
```
❯ docker pull cschranz/gpu-jupyter
Using default tag: latest
Error response from daemon: manifest for cschranz/gpu-jupyter:latest not found: manifest unknown: manifest unknown
```
Is it intentional? Doesn't it make sense to point to the latest image (v1.5_cuda-11.6_ubuntu-20.04 as of now).

**Comment by ChristophSchranz** [comment]
Hi @chessman 
GPU-Jupyter aims to create isolated environments for reproducible setups.
The `latest` tag contradicts this purpose, as it changes the setup version as soon as a later tag is pushed.
Even worse, as there are three branches `slim`, `python-only` and `full`, users wouldn't be aware which version they have and what packages should work!

Therefore, this purpose is intended, it nudges to use tags highly recommended for Docker anyways, even though a more precise feedback would be nice for those not familiar with Docker.
