### ISSUE TITLE
PyTorch 2 needs CUDA 11.7+

### ISSUE THREAD

**Issue by hlapp** [iot-salzburg/gpu-jupyter#119]
The latest CUDA version available among the prebuilt images on Docker Hub seems to be 11.6. However, apparently PyTorch2, which seems to be the version of PyTorch installed into the container, [needs 11.7+](https://pytorch.org/get-started/locally/). Are there plans to add pre-builds for later CUDA versions?

**Comment by hlapp** [comment]
Just to be clear, thinking that PyTorch2 is installed in the container was a mistake of mine.

**Comment by mathematicalmichael** [comment]
hm. i've been using torch 2 since release and don't recall rebuilding my images. are you able to just pip install it?

**Comment by hlapp** [comment]
The installation is ultimately unsuccessful because of the CUDA dependency. Of course, this only matters if using on GPU.

**Comment by benz0li** [comment]
@hlapp You may be interested in [b-data](https://github.com/b-data)'s/my GPU accelerated [JupyterLab](https://github.com/b-data/jupyterlab-r-docker-stack/blob/main/CUDA.md) [docker](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/CUDA.md) [stacks](https://github.com/b-data/jupyterlab-julia-docker-stack/blob/main/CUDA.md).

(currently) Based on [nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.8.0-cudnn8-devel-ubuntu22.04); including [code-server](https://github.com/coder/code-server) – aka VS Code in the browser.

**Comment by ChristophSchranz** [comment]
Hi,
new tags are available such as `v1.5_cuda-12.0_ubuntu-22.04_python-only` and `v1.5_cuda-11.8_ubuntu-22.04_python-only` which are based on [12.0.1-cudnn8-devel-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/12.0.1-cudnn8-devel-ubuntu22.04/images/sha256-7bd982c058fd5eb8070ce1a06f6fd3c5bdfbdc9243a54d2871940130dad56c35?context=explore) rsp. [11.8.0-cudnn8-devel-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/11.8.0-cudnn8-devel-ubuntu22.04/images/sha256-3fbac875b9fd3059d554226246c1ade676fad88aee1ac2cb2deaa6e77e4606a5?context=explore). Both are built with with PyTorch 2 and the latest compatible Tensorflow version.

Thiss issue should be solved with PR https://github.com/iot-salzburg/gpu-jupyter/pull/124
