### ISSUE TITLE
How to add new packages into the image ? 

### ISSUE THREAD

**Issue by leviethung2103** [iot-salzburg/gpu-jupyter#120]
Hello,

How can install the gcc inside the Docker container ? 

I got this error when installing the package 
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

**Comment by mathematicalmichael** [comment]
are you working with a volume that has the `nosuid` option on mount?

**Comment by ChristophSchranz** [comment]
Hi @leviethung2103, 
it is not clear what your setup is and how we can help you with that issue.
It should be possible to install via `apt-get`, `pip`, `conda`, compile with `gcc`, and build sources with `make` (both pre-installed).
Make also sure you have the right user permissions with `chmod` and `chown` for the data to process (see e.g. [here](https://stackoverflow.com/questions/46272880/cannot-open-new-jupyter-notebook-permission-denied)).
