### ISSUE TITLE
Unable to change conda environment in kernel

### ISSUE THREAD

**Issue by iguy0** [iot-salzburg/gpu-jupyter#121]
Hi,

I'm trying to add/change the conda/python environment and i'm unable to do so.

# Steps to reproduce:

docker run --gpus all -d -it -p 8848:8888 -v /home/USER:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root cschranz/gpu-jupyter:v1.5_cuda-11.6_ubuntu-20.04_python-only 

# Log into JupyterLab and add a different kernel/conda environment using the terminal
mkdir /home/jovyan/envs
conda init bash
exec $SHELL
conda create -p /home/jovyan/envs/python3.11 python=3.11
conda activate /home/jovyan/envs/python3.11 
pip install --user ipykernel
python -m ipykernel install --user --name=python3.11
conda deactivate
# at this point the kernel is available, but selecting the kernel gives me this
![2023-10-18 21_25_53-Untitled ipynb - JupyterLab and 60 more pages - Profile 1 - Microsoft​ Edge](https://github.com/iot-salzburg/gpu-jupyter/assets/15723895/22d6adcf-b0c1-4201-873d-3f722769b306)

Installing packages via pip and conda end up under /opt/conda when importing them uses the 3.11 environment, and gives a ImportError error. How to fix this ?

**Comment by benz0li** [comment]
@iguy0 See https://github.com/jupyter/docker-stacks/pull/2050.

FYI @mathematicalmichael

**Comment by ChristophSchranz** [comment]
Closing as there were no contributions for a while and it seems there is a workaround.
