### ISSUE TITLE
Update to Jupyterlab 4.0.10

### ISSUE THREAD

**Issue by kallegrens** [iot-salzburg/gpu-jupyter#131]
# GPU-Jupyter Feature Request

Thank you for your interest in enhancing GPU-Jupyter. We appreciate your ideas and feedback. Please fill out this brief form to help us understand your feature request.

## Feature Description

**Title**
Update to Jupyterlab 4.1

**Detailed Description**
> JupyterLab is now faster, thanks to improvements such as CSS rules optimization, CodeMirror 6, MathJax 3, and notebook windowing. By rendering only the parts of a notebook that fit in the web browser viewport, JupyterLab 4 is much more efficient than JupyterLab 3 was when working with large notebooks.
– Jupyter blog

**Benefits**
For the same reasons mentioned when deciding to upgrade to Jupyterlab 3.x in [#44 ](https://github.com/iot-salzburg/gpu-jupyter/issues/44)

**Possible Implementation**

## Additional Information

**Screenshots/Illustrations**

**References**
[v4.0 changelog](https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-0)
[Jupyter blog](https://blog.jupyter.org/jupyterlab-4-0-is-here-388d05e03442)
---

*We value your contribution and look forward to exploring new features for GPU-Jupyter. Thank you for your support!*

**Comment by kallegrens** [comment]
Nowhere in the generated Dockerfile is `juptyterlab==3.6.6` mentioned. However, there are two extensions which don't yet support juptyterlab 4+. These are `jupyterlab-drawio==0.9.0` and `jupyterlab-spellchecker==0.7.3`. However, the newer version 0.8.3 of spellchecker supports jupyterlab 4+. 

I successfully built my own image with jupyterlab 4, simply without jupyterlab-drawio and with the updated spellchecker. 

jupyterlab-drawio seems no longer to be maintained. The actively maintained [`ipydrawio`](https://github.com/deathbeds/ipydrawio) does not yet support it either. The issue tracking this is: [https://github.com/deathbeds/ipydrawio/issues/119](https://github.com/deathbeds/ipydrawio/issues/119).

**Comment by ChristophSchranz** [comment]
Hi @kallegrens,
thanks for the suggestion and info! The GPU-Jupyter project inherits jupyterlab-related changes from the [docker-stacks](https://github.com/jupyter/docker-stacks/tree/main) and will build images with Jupyterlab 4.X as soon as docker-stacks supports them and is stable enough for the update. 

I've subscribed to https://github.com/deathbeds/ipydrawio/issues/119 and will build new images if there is a solution or if there won't be any without this package.

**Comment by mkarikom** [comment]
Just wondering if I messed up my image build somehow?
I'm currently on `v1.6_cuda-12.0_ubuntu-22.04` but it still seems to be built with `jupyterlab==3.6.7`
Regarding the comments above, I noticed that currently [docker-stacks[main]](https://github.com/jupyter/docker-stacks?tab=readme-ov-file#quick-start) seems to be making [images with 4.1.3](https://mybinder.org/v2/gh/jupyter/docker-stacks/main?urlpath=lab/tree/README.ipynb).

**Comment by ChristophSchranz** [comment]
Hi @mkarikom 
The image `v1.6_cuda-12.0_ubuntu-22.04` was built based on the commit `1494233e27cdc70e3766ea2518e7153ee425fc4f` of [docker-stacks](https://github.com/jupyter/docker-stacks). This one comes with `jupyterlab==3.6.7`. 
It is good to hear that docker-stacks now supports Jupyterlab version 4.X.

I will check the Jupyterlab version and also the PyTorch compatibility with CUDA 12.3 (issue https://github.com/iot-salzburg/gpu-jupyter/issues/140) and then build a new image with an updated docker-stacks hash.

**Comment by ChristophSchranz** [comment]
Unfortunately, drawio still doesn't support JupyterLab 4.X.
```
(base) jovyan@d07e814f66eb:~/work/Getting_Started$ conda install -c conda-forge jupyterlab-drawio
Channels:
 - conda-forge
 - nvidia
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - jupyterlab-drawio


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiofiles-22.1.0            |     pyhd8ed1ab_0          17 KB  conda-forge
    aiosqlite-0.19.0           |     pyhd8ed1ab_0          19 KB  conda-forge
    jupyter_client-7.4.9       |     pyhd8ed1ab_0          97 KB  conda-forge
    jupyter_server_fileid-0.9.1|     pyhd8ed1ab_0          20 KB  conda-forge
    jupyter_server_ydoc-0.8.0  |     pyhd8ed1ab_0          15 KB  conda-forge
    jupyter_ydoc-0.2.4         |     pyhd8ed1ab_0          78 KB  conda-forge
    jupyterlab-3.6.7           |     pyhd8ed1ab_0         5.4 MB  conda-forge
    jupyterlab-drawio-0.9.0    |     pyhd8ed1ab_0         624 KB  conda-forge
    jupyterlab-git-0.44.0      |     pyhd8ed1ab_0         531 KB  conda-forge
    jupyterlab_pygments-0.3.0  |     pyhd8ed1ab_0          18 KB  conda-forge
    nbdime-3.2.1               |     pyhd8ed1ab_0         3.8 MB  conda-forge
    notebook-6.5.6             |     pyha770c72_0         299 KB  conda-forge
    pyzmq-24.0.1               |  py311ha4b6469_1         573 KB  conda-forge
    y-py-0.5.9                 |  py311hfe55011_0         1.2 MB  conda-forge
    ypy-websocket-0.8.2        |     pyhd8ed1ab_0          17 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.7 MB

The following NEW packages will be INSTALLED:

  aiofiles           conda-forge/noarch::aiofiles-22.1.0-pyhd8ed1ab_0 
  aiosqlite          conda-forge/noarch::aiosqlite-0.19.0-pyhd8ed1ab_0 
  jupyter_server_fi~ conda-forge/noarch::jupyter_server_fileid-0.9.1-pyhd8ed1ab_0 
  jupyter_server_yd~ conda-forge/noarch::jupyter_server_ydoc-0.8.0-pyhd8ed1ab_0 
  jupyter_ydoc       conda-forge/noarch::jupyter_ydoc-0.2.4-pyhd8ed1ab_0 
  jupyterlab-drawio  conda-forge/noarch::jupyterlab-drawio-0.9.0-pyhd8ed1ab_0 
  y-py               conda-forge/linux-64::y-py-0.5.9-py311hfe55011_0 
  ypy-websocket      conda-forge/noarch::ypy-websocket-0.8.2-pyhd8ed1ab_0 

The following packages will be DOWNGRADED:

  jupyter_client                         8.6.1-pyhd8ed1ab_0 --> 7.4.9-pyhd8ed1ab_0 
  jupyterlab                             4.1.5-pyhd8ed1ab_0 --> 3.6.7-pyhd8ed1ab_0 
  jupyterlab-git                        0.50.0-pyhd8ed1ab_1 --> 0.44.0-pyhd8ed1ab_0 
  jupyterlab_pygmen~                     0.3.0-pyhd8ed1ab_1 --> 0.3.0-pyhd8ed1ab_0 
  nbdime                                 4.0.1-pyhd8ed1ab_0 --> 3.2.1-pyhd8ed1ab_0 
  notebook                               7.1.2-pyhd8ed1ab_0 --> 6.5.6-pyha770c72_0 
  pyzmq                              25.1.2-py311h34ded2d_0 --> 24.0.1-py311ha4b6469_1 


Proceed ([y]/n)?
```
I suggest closing this issue with the support of Juypterlab 4.1, as [drawio](https://github.com/QuantStack/jupyterlab-drawio/issues/119) seems to be not actively maintained at the moment.

**Comment by ChristophSchranz** [comment]
Closing with https://github.com/iot-salzburg/gpu-jupyter/pull/144
