### ISSUE TITLE
How do I fit this image in CentOS 7?

### ISSUE THREAD

**Issue by Guanzhou-Ke** [iot-salzburg/gpu-jupyter#14]
This is a good project. But my OS is CentOS 7. So, how should I fit it in my OS if I really want to use it. May be it could fix my cuda problem.

**Comment by ChristophSchranz** [comment]
There seems to be a bug as @mathematicalmichael reported in issue #15 (he also suggests a solution).
There will be commit soon.

Another: does `docker run --runtime nvidia nvidia/cuda:10.1-base-ubuntu18.04 nvidia-smi` yield the expected output?

**Comment by ChristophSchranz** [comment]
The commit ffe73f572f247126fa446a344244ce0e4bc8a0ab could have solved your problem.

**Comment by Guanzhou-Ke** [comment]
I had been solved it, I re-made a image based on nvidia/cuda:10.1-base-ubuntu18.04. It running. Thanks.
