### ISSUE TITLE
Upgrade to latest versions (e.g. CUDA 12.3)

### ISSUE THREAD

**Issue by fzyzcjy** [iot-salzburg/gpu-jupyter#140]
Hi thanks for the docker container! It would be great to upgrade to latest versions, such as CUDA 12.3 which is released https://hub.docker.com/r/nvidia/cuda/tags

**Comment by ChristophSchranz** [comment]
Hi @fzyzcjy 
thanks for the feature request.

While Tensorflow already supports CUDA 12.3 ([here](https://www.tensorflow.org/install/source#gpu)), PyTorch compatibility is not fully clear to me yet. Officially CUDA 12.1 is supported ([here](https://pytorch.org/get-started/locally/)) but it could be already built from source ([here](https://discuss.pytorch.org/t/there-is-no-option-pytorch-for-cuda-12-2-and-latest-12-3/193755/2)).

I suggest to wait until CUDA 12.3 is installable via pip.

**Comment by fzyzcjy** [comment]
Looks reasonable, thank you!

**Comment by ChristophSchranz** [comment]
Closing with https://github.com/iot-salzburg/gpu-jupyter/pull/144
