### ISSUE TITLE
Suggest way to use latest pytorch (2.2.2)

### ISSUE THREAD

**Issue by fzyzcjy** [iot-salzburg/gpu-jupyter#142]
Hi thanks for the package! It seems that https://pytorch.org/get-started/locally/ says the stable version is 2.2.2 with CUDA 12.1. However, it seems that the image has cuda 12.0 with pytorch 2.1.2 (see https://github.com/iot-salzburg/gpu-jupyter/blob/db4aa300fc95685fd7c687911c0e66917c89bc85/custom/gpulibs.Dockerfile#L28). Therefore, how should I upgrade? For example, should I `pip install -U` directly (will it cause some hidden problems?)

Related: https://github.com/iot-salzburg/gpu-jupyter/issues/140

**Comment by ChristophSchranz** [comment]
Hi @fzyzcjy ,
the suggested way to update a package within the container is `pip install [package]==[version]`.
The flag `-U` will upgrade the package to the latest version that might not support the current CUDA version [pip flag -U](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-U).

**Comment by fzyzcjy** [comment]
Thank you! Then another question is, how should I upgrade CUDA - should I wait for the image or there are other methods?

**Comment by benz0li** [comment]
@fzyzcjy You could use my/b-data's [GPU accelerated Python images](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/CUDA.md):

`glcr.b-data.ch/jupyterlab/cuda/python/scipy:3.12`

* based on `nvidia/cuda:12.4.1-devel-ubuntu22.04`
  * including a custom cuDNN 8 installation

Install TensorFlow: `pip install tensorflow`

Install PyTorch: `pip install torch torchvision torchaudio`

---

**What is different about my/b-data's images:**

1. Multi-arch: `linux/amd64`, `linux/arm64/v8`
1. Derived from [`nvidia/cuda:12.4.1-devel-ubuntu22.04`](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=12.4.1-devel-ubuntu22.04)
    * including development libraries and headers
1. TensortRT and TensorRT plugin libraries
    * including development libraries and headers
1. IDE: [code-server](https://github.com/coder/code-server) next to [JupyterLab](https://github.com/jupyterlab/jupyterlab)
1. Just Python – no [Conda](https://github.com/conda/conda) / [Mamba](https://github.com/mamba-org/mamba)

---

There are also Python 3.11 images, which are still derived from [`nvidia/cuda:11.8.0-cudnn-devel-ubuntu22.04`](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.8.0-cudnn8-devel-ubuntu22.04):

`glcr.b-data.ch/jupyterlab/cuda/python/scipy:3.11`

* based on `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`

Install TensorFlow: `pip install tensorflow==2.14.1`

Install PyTorch: `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

**Comment by fzyzcjy** [comment]
Thanks! I will have a look at it when next time working on infra.
