### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by mathematicalmichael** [iot-salzburg/gpu-jupyter#15]
Steps:

./generate_dockerfile.sh --slim

bash start-local.sh -p 8888 

Error:

failed to build, step 25. getting miniconda. Perhaps a link broke?

**Comment by mathematicalmichael** [comment]
docker build -t gpu-jupyter .build/

does work (seems to pick up from cache last week)

**Comment by mathematicalmichael** [comment]
I think this is an issue pertaining to the focal ubuntu image, a bug it seems that I encountered elsewhere as well.

adding `RUN chmod 1777 /tmp` right below the reference to the focal image in `.build/Dockerfile` allows step 25 (now step 26) to work. don't want to jinx it but my build is now on step 29, so it looks fine from here...

**Comment by ChristophSchranz** [comment]
Yes I that's possible. Your build was working in the end, right?

Those lines origin from the docker-stack Dockerfiles:
https://github.com/jupyter/docker-stacks/blob/04f7f60d34a674a2964d96a6cb97c57a7870a828/base-notebook/Dockerfile#L11-L17

It is necessary to make a PR on this Dockerfile, or do you think that there is an uncomplicated work-around, like choosing a version before focal?

**Comment by mathematicalmichael** [comment]
yes I got it building by adding the one-liner. 
so, focal from june seems fine without it, but frankly, that line really _cant_ hurt from a robustness perspective. 

the github actions seems to pass as-is, but it might be using a cached version of ubuntu, I don't know.

**Comment by ChristophSchranz** [comment]
Your PR ffe73f572f247126fa446a344244ce0e4bc8a0ab is merged, I suppose this issue is solved and can be closed.

**Comment by mathematicalmichael** [comment]
surprised it didn't close automatically since it was mentioned in the comments.
