### ISSUE TITLE
CUDA 12.1 support?

### ISSUE THREAD

**Issue by fzyzcjy** [iot-salzburg/gpu-jupyter#151]
Hi thanks for the docker image! I would like to have a try on https://github.com/unslothai/unsloth, but it says we need cuda 12.1. However, in https://hub.docker.com/r/cschranz/gpu-jupyter/tags?page=&page_size=&ordering=&name=, there is 12.0 and 12.2, but missing 12.1.

**Comment by ChristophSchranz** [comment]
Hi @fzyzcjy,

yes, that's true, this version was skipped, and it is not considered to be built.

**Comment by fzyzcjy** [comment]
Thank you all the same... Btw curious why?

**Comment by ChristophSchranz** [comment]
The main purpose of the Docker-images are to provide a fast to setup Data Science environment with Tensorflow and PyTorch libraries, and a basis for additional high-level GPU-libraries. The Git-Repository helps to make some adaptations and allowing to build custom images, such as for varying GPU-libraries. This can be done perfectly using the current setup as described in https://github.com/iot-salzburg/gpu-jupyter?tab=readme-ov-file#build-your-image.
