### ISSUE TITLE
Pre build all nvidia/cuda tags for users who can't build it successfully.

### ISSUE THREAD

**Issue by TaylorHere** [iot-salzburg/gpu-jupyter#19]

**Comment by ChristophSchranz** [comment]
Tell me more. ;)

**Comment by maresb** [comment]
Did you ever look into DockerHub?

**Comment by ChristophSchranz** [comment]
@TaylorHere can you please explain to me how I can access your tagged images?

**Comment by mathematicalmichael** [comment]
@ChristophSchranz quick Q: are you manually updating the dockerhub? 
If so, we can discuss adding directives to 
https://github.com/iot-salzburg/gpu-jupyter/blob/master/.github/workflows/main.yml
which perform that function automatically. If this is something you're interested in, open a new issue and I can help close it out. you'll just need to add your dockerhub token to the secrets of this repo.

**Comment by ChristophSchranz** [comment]
That would be great!
