### ISSUE TITLE
CUDA not found

### ISSUE THREAD

**Issue by tristanstoeber** [iot-salzburg/gpu-jupyter#22]
Hey, 

thanks for putting these dockerfiles online!
I tried building and running them, but despite confirmative output at 
docker run --gpus all nvidia/cuda:10.1-base-ubuntu18.04 nvidia-smi

> NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0

cuda is not available in pylabs. "torch.cuda.is_available()" returns "False".
"!nvidia-smi" in the notebook does also not work: "/bin/bash: nvidia-smi: command not found"

Any clue what could have gone wrong?

Best,
Tristan

Further infos:
- Docker version 19.03.12, build 48a66213fe
- docker-compose version 1.17.1, build unknown
- Ubuntu 18.04

**Comment by tristanstoeber** [comment]
adding "--gpus all" to 

docker run -d -it -p 8848:8888 --gpus all -v $(pwd)/data:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root --restart always --name gpu-jupyter_1 gpu-jupyter 

fixed the problem.

I came to the solution by trying to follow
>https://medium.com/@christoph.schranz/set-up-your-own-gpu-based-jupyterlab-e0d45fcacf43
There
>docker run --runtime nvidia nvidia/cuda:10.1-base-ubuntu18.04 nvidia-smi
did not work. 

A solution has been suggested here:
https://github.com/NVIDIA/nvidia-docker/issues/838

**Comment by mathematicalmichael** [comment]
@tristanstoeber I had a similar issue, it depends on how docker-nvidia was installed.
https://github.com/iot-salzburg/gpu-jupyter/issues/16#issuecomment-660540650 see link here + previous convo. In order to get the shell script included here working, rather than pass `--gpus all` (or `--gpus device=1` in my case) each time.
