### ISSUE TITLE
Running locally - any risks with the user "jovyan"?

### ISSUE THREAD

**Issue by Jollyhrothgar** [iot-salzburg/gpu-jupyter#28]
I found this repo after a lot of struggling with setting up a docker image where I could run GPU accelerated TensorFlow with all the various creature comforts I've grown used to (jupyter lab plugins, access to local storage, modify which local files are shared or not, etc). You can see my pitiful attempts to set up [here](https://github.com/Jollyhrothgar/deep_learning), but it looks like you folks have solved most of the problems I've encountered already.

It seems like this repo contains everything one would need to get started - but I had some concerns about running the setup scripts on my local machine - there are a lot of references to a specific username "jovyan", hard-coded local directory structure, as well as modifications to the passwd file.

I'm curious if this repo has been configured for one person to run and I'm just looking at a public repo of a passion project, or if its ok to run on my local machine without clobbering the passwd file with stuff that will mess up my ability to login?

Thanks!!

**Comment by mathematicalmichael** [comment]
you're good. you came to the right place, friend. we too have struggled and this repo is meant to be a shortcut to success through the magic of (nvidia-)docker. 

it's meant for public consumption and is a gpu-based version of jupyter/docker-stacks, and will eventually mirror the naming conventions of that project more closely. `jovyan` is a "Jupyter inside joke" and refers to a "user of jupyter" 
Like that project, the idea is to mount all "work" that is meant to persist in `/home/jovyan/work` in the container. 

`jovyan` is just the username of the account you'll have in the container once you launch it. It's mapped to UID 1000 so any files you create under it will appear as if they belong to whomever is mapped to that UID on your system.

**Comment by mathematicalmichael** [comment]
more info: https://jupyter-docker-stacks.readthedocs.io/en/latest/
reference: https://github.com/jupyter/docker-stacks/issues/358#issuecomment-288844834

**Comment by Jollyhrothgar** [comment]
Thanks - I set it all up and got it running - so awesome. Its great to see projects like this - worked like a charm for me. Any advice for how to modify to further customize? I've been basically just modifying the `Dockerfile` under `.build` to add some additional libraries (e.g. tensorflowdataset, a vim-code-cell plugin) - but the rebuild takes about an hour+ for each change.

I can see that I can specify sub-components that I want to build (for example, I don't really use R, Julia, or docker-swarms) - any advice on how to sort of quickly customize this into a lean-er package that fits like a glove? I can also just do some trial/error/googling, but in case I'm missing some short-cut, I thought I'd ask.

Thanks again!

**Comment by mathematicalmichael** [comment]
Happy to hear that! 

You can add things on to the _bottom_ of the resulting dockerfile (see `./generate-dockerfile` for more info), to take advantage of docker's caching layers feature. What you're asking for re: the packaged languages will be addressed in #27 but currently is supported by using the flags for slim images: https://github.com/iot-salzburg/gpu-jupyter/issues/16#issuecomment-657639689 I think you notably want to exclude the datascience stack, which won't be part of the new default.

**Comment by ChristophSchranz** [comment]
Thanks @Jollyhrothgar!

There are options to reduce the size of the image.
In particular, you can generate a Dockerfile in `.build/` without `Julia` and `R` if you run:

```bash
bash generate-Dockerfile.sh --no-datascience-notebook
```
and without the additional languages and packages with:
```bash
bash generate-Dockerfile.sh --slim
```
It is true that most people here will use Python only. I'll improve the description and change the default example.

See section [Parameter](https://github.com/iot-salzburg/gpu-jupyter#parameter) for more information.

**Comment by ChristophSchranz** [comment]
I close this issue as i think all points are clear now. Reopen if not.
