### ISSUE TITLE
Unable to install any Debian based packages

### ISSUE THREAD

**Issue by nsudhanva** [iot-salzburg/gpu-jupyter#32]
I have a terminal open and I'm trying to install a new Debian package through apt or apt-get. 

**Example:**

![image](https://user-images.githubusercontent.com/11288918/95552236-fda02580-0a29-11eb-9d5a-f9ceec255a5c.png)

It asks for a password for the user 'jovyan'

_or_ 

It shows this without the `sudo`

![image](https://user-images.githubusercontent.com/11288918/95552360-34763b80-0a2a-11eb-8f98-dfd16f70d95e.png)

Looking at [this issue](https://github.com/jupyter/docker-stacks/issues/408#issuecomment-321688968) tells that the parameter  `-e GRANT_SUDO=yes` to the user `jovyan` will solve it. Looking at [your Dockerfile](https://hub.docker.com/r/cschranz/gpu-jupyter/dockerfile) reveals that this parameter doesn't exist. Is there a possible help on where I can add this to the Docker file or how I can fix this?

Thanks

**Comment by ChristophSchranz** [comment]
Hi @nsudhanva,
the environment variable `GRANT_SUDO` is used by the Jupyter instance itself. This design decision isn't useful if you use the GPU-Jupyter mostly yourself, but it is if you provide the Jupyter service to others and want to prohibit the installation of packages. 

If you want to set this always to true, you could [set the env variable in the Dockerfile](https://stackoverflow.com/questions/59932994/how-to-set-environment-variables-in-dockerfile-via-azure-devops), or better in `src/Dockerfile.usefulpackages`. E.g.:

    GRANT_SUDO=yes
