### ISSUE TITLE
logo for gupyter

### ISSUE THREAD

**Issue by ChristophSchranz** [iot-salzburg/gpu-jupyter#33]
As the popularity of this project grows, I would like to propose a logo for this project:

![logo_gupyter](https://user-images.githubusercontent.com/16668897/96592606-ddede480-12e8-11eb-91d1-5b28c7f3d653.png)

It's style is inspired by the main Jupyter project and has the following characteristics:
* can be pronounced as gupyter or gpupyter as proposed by @mathematicalmichael in https://github.com/iot-salzburg/gpu-jupyter/issues/27
* the orange bows and points hint the top and bottom parts of G, P, and U behind the "gupyter"

What do you say? Should the bows and points be differently aligned?
Should this also be discussed with someone from the Jupyter foundation?

I'm also available on Facebook with my clear name and twitter as IoTChris.

**Comment by mathematicalmichael** [comment]
hey Chris! 
I'd like to try and keep it in the same aspect ratio; do you think much of this complexity would be reduced if we just drop the "p" in "gpu"? definitely support the orange g, but feel we should be closer to the original.

I'll DM you on twitter!

**Comment by ChristophSchranz** [comment]
What about this?
![grafik](https://user-images.githubusercontent.com/16668897/96689105-42a94d80-1382-11eb-8534-e68795fb4d5c.png)

**Comment by ChristophSchranz** [comment]
The `p` could also be used as apostrophe.
![grafik](https://user-images.githubusercontent.com/16668897/96705530-b6a12100-1395-11eb-8a80-38c9f184faf8.png)

**Comment by mathematicalmichael** [comment]
I still think it's harder to recognize (and do remember that this will most often appear in a small icon). could I please see it with no p at all? or do you think without the "p" the connection to GPUs isn't clear enough?

**Comment by ChristophSchranz** [comment]
Do you mean something like:
1)
![grafik](https://user-images.githubusercontent.com/16668897/96749405-1239d180-13cb-11eb-8920-42c579f04e9a.png)
2)
![grafik](https://user-images.githubusercontent.com/16668897/96749460-267dce80-13cb-11eb-9cc7-29690db62291.png)
3)
![grafik](https://user-images.githubusercontent.com/16668897/96749485-2e3d7300-13cb-11eb-867b-21f0c930a5d7.png)
4)
![grafik](https://user-images.githubusercontent.com/16668897/96749685-6cd32d80-13cb-11eb-9491-3fbfc9f042f0.png)

Which one do you like most?

**Comment by mathematicalmichael** [comment]
@elliottregan could you give this a stab? would appreciate your design skills.
@ChristophSchranz i was thinking a lower g and more similar to the original. I can't not see the smiley face.

**Comment by elliottregan** [comment]
@mathematicalmichael I can create an SVG version as well, GitHub just wasn’t letting me upload one into the comments.
![Jupyter_logo 2](https://user-images.githubusercontent.com/950202/97098672-4b7d7600-1645-11eb-845c-0dac0daa4e82.png)

**Comment by elliottregan** [comment]
![Jupyter_logo 2](https://user-images.githubusercontent.com/950202/97098681-867fa980-1645-11eb-89d6-5d02608e81e7.png)

**Comment by ChristophSchranz** [comment]
Thanks @elliottregan 
I also have a legal question: how distinct should the gupyter logo be from the jupyter?

**Comment by elliottregan** [comment]
Here are their branding guidelines, which just covers fonts and basic things you shouldn’t do when representing Jupyter’s brand: https://github.com/jupyter/design

Since this project is a fork of the main Jupyter project, I’d have to assume it falls under the license as the code does. Not really sure though. You’re not trying to create your own library or anything, just adding features to their main product. They show examples of “Powered with Jupyter” in their branding guidelines, but I’m not sure if that is applicable here.

In any case, I wouldn’t worry about it. You’re not making money from this project.  If they feel it is too similar to the original, the only thing their team will do is ask you to change your logo.

**Comment by mathematicalmichael** [comment]
> @mathematicalmichael I can create an SVG version as well, GitHub just wasn’t letting me upload one into the comments.
> ![Jupyter_logo 2](https://user-images.githubusercontent.com/950202/97098672-4b7d7600-1645-11eb-845c-0dac0daa4e82.png)

seeing it this small is really helpful, represents what it will look like as an icon. i can tell pretty easily that it's a "g" there. What do you think of making it orange? too much?

**Comment by elliottregan** [comment]
![Jupyter_logo 3](https://user-images.githubusercontent.com/950202/97234429-67e4f400-17a6-11eb-8ba7-33c630a6be7e.png)

I prefer the black/dark grey version more. It’s going to be easier to read, and you don’t want to use too many “tricks”.  The darker color should be just enough to call attention to the “g” without being busy. 

Your target users will be people already familiar with Jupyter, and hopefully the “g” should catch their attention to make them want to learn more.

**Comment by ChristophSchranz** [comment]
Nice logos @elliottregan 
would you like to share a png, svg and ico here or in a PR in the directory `./extra/logo/`?
I personally prefer the orange one, maybe we should upload both versions. 

Is it possible to make the orange of the g slighly darker? It seems brighter than the other orange.

**Comment by mathematicalmichael** [comment]
> Nice logos @elliottregan
> would you like to share a png, svg and ico here or in a PR in the directory `./extra/logo/`?
> I personally prefer the orange one, maybe we should upload both versions.
> 
> Is it possible to make the orange of the g slighly darker? It seems brighter than the other orange.

agree, I think the gray/black are easier to read than the orange. I suspect... that maybe it's actually the same color but looks brighter because of the relative proportion of white surrounding it.

**Comment by mathematicalmichael** [comment]
> @mathematicalmichael I can create an SVG version as well, GitHub just wasn’t letting me upload one into the comments.
> ![Jupyter_logo 2](https://user-images.githubusercontent.com/950202/97098672-4b7d7600-1645-11eb-845c-0dac0daa4e82.png)

seeing it this small is really helpful, represents what it will look like as an icon. i can tell pretty easily that it's a "g" there. What do you think of making it orange? too much?

**Comment by ChristophSchranz** [comment]
Closing with commit 0fbee0559663771dcb1fa7098e31cb44e9424664, added a logo in the README
