### ISSUE TITLE
Changing tensorflow-gpu to tensorflow

### ISSUE THREAD

**Issue by ArthurKwok** [iot-salzburg/gpu-jupyter#35]
Hello,

Thanks a lot for maintaining this Docker image.
Starting from tensorflow 2.0, there's no separate version for CPU or GPU. 
See this page: https://www.tensorflow.org/install/gpu
Therefore if you do `pip install tensorflow-gpu>=2.0.*`, it is actually an alias of doing `pip install tensorflow>=2.0.*`. The latter one will also have all GPU libraries.
However in the current latest version of gpu-jupyter, if someone do `pip install tensorflow`, there will be two identical tensorflows in the system.
I'm not sure if this should be an issue of gpu-jupyter or tensorflow itself, but I guess it is somehow better to get rid of the name `tensorflow-gpu`.

Thanks very much for reading,
Arthur Guo

**Comment by ChristophSchranz** [comment]
Thanks for your info and sorry for the late response!

Changed this in 6a7acdecce5a66f036af66b7debf2fc30e5faa77
