### ISSUE TITLE
how to add jupyterlab-git into the image?

### ISSUE THREAD

**Issue by mclockw** [iot-salzburg/gpu-jupyter#36]
I am trying to add jupyterlab-git(https://github.com/jupyterlab/jupyterlab-git) into this image, but don't know what is the right way to do. Does anybody know how to ?

**Comment by mathematicalmichael** [comment]
```
pip install --upgrade jupyterlab jupyterlab-git
jupyter lab build
```

into https://github.com/iot-salzburg/gpu-jupyter/blob/master/src/Dockerfile.usefulpackages
for that particular flavor of build.
