### ISSUE TITLE
why this package? + some security considerations

### ISSUE THREAD

**Issue by mathematicalmichael** [iot-salzburg/gpu-jupyter#38]
https://github.com/iot-salzburg/gpu-jupyter/blob/03392f4136e3f98e394f023b0059387a6f79c590/.build/Dockerfile#L364-L367

I noticed it's not working anyway due to permissions. But moreover, I'm investigating thousands of chinese-origin `POST` requests to `/login?next=%2Ftree%3F` polluting my jupyter logs and noticed this while doing so:

```
$ docker logs -f jupyter-2
Set username to: jovyan
usermod: no changes
Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
Executing the command: jupyter notebook
[I 04:47:57.325 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[INFO 2021-01-21 04:47:57.457 TabNine]:  install dir: /opt/conda/lib/python3.7/site-packages/jupyter_tabnine
[INFO 2021-01-21 04:47:57.589 TabNineDownloader]: Begin to download TabNine Binary from https://update.tabnine.com/3.2.28/x86_64-unknown-linux-gnu/TabNine
[ERROR 2021-01-21 04:47:57.590 TabNineDownloader]: Download failed, error: [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/jupyter_tabnine/binaries'
```

The reason I started investigating this was because my GPU was running 150W for an indeterminate amount of time without me having kicked off any work. When I killed the singular docker process, the GPU calmed down immediately, so I'm sure the jupyter instance was responsible for the GPU. That of course makes the aforementioned `POST` requests especially fun... yay security!

**My suggestion is we immediately change the default password.**

**Comment by mathematicalmichael** [comment]
confirmed. looked through my logs. brute force attempt eventually cracked the default password. my fault for leaving it open.
attackers set up cryptomining on the system.

**Comment by ChristophSchranz** [comment]
Okay, interesting. I suggest we install `tabnine` (for auto-completion) via pip (`pip install jupyter-tabnine`) and change the default password. I admit, `asdf` was not intelligent, as it is short and used so often!
`gpu-jupyter` or `gupyter` would be better (at least if there is no web-scraper that extracts the password from the README). What do you think?

**Comment by mathematicalmichael** [comment]
what's wrong with the default `jedi`? I don't know if I need "deep learning" in my autocompletion

**Comment by ChristophSchranz** [comment]
Okay, do you think `asdf` was cracked because it is frequent? The number of characters would be the same.  
As far as I know, some autocompletion algorithms use a recurrent network that estimates the propability of the next chars or valid variables/functions. I've also got used to that ;)

**Comment by ChristophSchranz** [comment]
Regarding `jedi`, there could be a webscraper that realizes that many Jupyter instances have that default password.
Maybe `gpu-jedi` would be better. What do you think?

**Comment by ChristophSchranz** [comment]
I've prepared a commit to solve the issues discussed here. Just let me know what password you prefer!

**Comment by mathematicalmichael** [comment]
@ChristophSchranz I do think `asdf` was too frequent. a phrase is much more secure. maybe something less guessable like `gupyter_notebook`? 

and I don't follow re: `jedi`. What do you mean?

**Comment by mathematicalmichael** [comment]
(also to be clear, my main security flaw was opening the port to the internet instead of using a VPN... a stronger password would have been a second line of defense but ultimately the blame is on me for leaving the gate wide open and inviting intruders)

**Comment by ChristophSchranz** [comment]
Ohh, I thought you suggested `jedi` as password.

**Comment by ChristophSchranz** [comment]
@mathematicalmichael It happens easily that we forget about the first line of defense, therefore there should be a password that offers some defence ;)

**Comment by ChristophSchranz** [comment]
Hi,
I've changed the default password to `gpu-jupyter` (easy to remember and long enough) in af575a93be7de4785cae8599cb71aaaee94e7b2a
I've also solved an issua with tabnine, such that it is installed for a user in cd12d58ab867b2de09cefceee3b3b9277a9fc762.

Are you okay with those changes?

**Comment by mathematicalmichael** [comment]
also `jedi` is also not perfect (I had to downgrade yesterday to get tab-completion working in ipython ... it was crashing the session with every tabulation), will let you know if I have any issues with `tabnine`.
