### ISSUE TITLE
cannot create container

### ISSUE THREAD

**Issue by dsnalzami** [iot-salzburg/gpu-jupyter#39]
today, when I want to create container of cschranz/gpu-jupyter:latest, it got error message like this:

Failure OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "tini": executable file not found in $PATH: unknown

how to fix this?

also, my current container also did not responding, to status 302

**Comment by ChristophSchranz** [comment]
What is your output of: `docker run --gpus all nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 nvidia-smi`?

Are you root? You might run it with `sudo`.

**Comment by dsnalzami** [comment]
thank you, I found the culprit. Somehow my computer needs restart to fix the problem. My OS is Ubuntu Desktop 20.04.1 LTS.

I opened this issues due to I have two computers, one is on Ubuntu Desktop, other is Centos Server.
