### ISSUE TITLE
Update to Jupyterlab 3.x

### ISSUE THREAD

**Issue by edurenye** [iot-salzburg/gpu-jupyter#44]
https://github.com/jupyter/docker-stacks has updated to Jupyterlab 3.x

We should do the same but make sure that all extensions we use work well with it.

Right now I tested and the 'slim' version and works fine out of the box. But the 'useful packages' version breaks.
So before update we will have to deal with those packages or see if they still make sense, since due to the changes in 3.x they added functionality that was in some extensions, so some are no longer needed.

Another change is that now some extensions are installed using pip or conda.

We can check them here: https://github.com/jupyterlab/jupyterlab/issues/9461

**Comment by ChristophSchranz** [comment]
Thanks for the info :relaxed:
I've check this out

**Comment by edurenye** [comment]
I checked and seems like the only extension that we use that is not updated yet is jupyterlab/github https://github.com/jupyterlab/jupyterlab-github/issues/111

I'll prepare a PR for this that excludes that extension and updates the rest.

**Comment by edurenye** [comment]
Hi @ChristophSchranz, I see that in the last commit 958e6876ece2309482f9f2841a635a9b1f2a1f93 'update to Jupyterlab 3.x with updated tags' you added this:
`RUN pip install --upgrade jupyterlab jupyterlab-git`
to .build/Dockerfile but not to src/Dockerfile.usefulpackages that is the one that will generate the .build/Dockerfile if we use the generate script. So that file need to be changed accordingly.
Also I don't understand why we use the `export TAGNAME="v1.4_cuda-11.0_ubuntu-18.04"` if the image is still `FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04`, so is still cuda 10.1.

**Comment by edurenye** [comment]
Hi @ChristophSchranz, I see that you reverted this commit, then I think this issue should be reopened.

In the revert message you mention that some packages are not compatible enough, could you elaborate please? Which packages are those? Maybe we can help them to update.

As I said before the only one that was not updated yet was jupyterlab/github but seems like you found a replacement for it, the https://github.com/jupyterlab/jupyterlab-git that works on 3.x, so I do not understand the problem?

Is it becuse of RISE? RISE never worked with jupyterlab and when it does will be directly for 3.x https://github.com/damianavila/RISE/issues/270

**Comment by ChristophSchranz** [comment]
Hi @edurenye 
there were issues when rebuilding and installing the latest commit, see https://github.com/iot-salzburg/gpu-jupyter/issues/47.
Sorry for this!  
Now, this should be fixed. The packages are replaced. The reason why RISE was not removed yet, is that it is still usable via `/notebooks`. As soon as RISE works for jupyterlab, I'll update it.

Can we close the issue from your side?

**Comment by edurenye** [comment]
Hi @ChristophSchranz thanks for your time and help.

I did not try the rollback or the last version, I can test it when I find time.

The only thing I'm concerned about it that the rollback was not a full rollback, was just changing the Dockerfile, that gets altered when you use the generate script: https://github.com/iot-salzburg/gpu-jupyter/commit/a9baf83453f4fcca8ab6d758294155cc12e10d03

And now in https://github.com/iot-salzburg/gpu-jupyter/commit/6a9a401abfd5764220b3f3ab927827c4abb99bae I see that you just update the generate script but not the Dockerfile or at least not the same changes are done.

So for example the `src/Dockerfile.usefulpackages` where not uncommented back.

And previous to all this in the commit https://github.com/iot-salzburg/gpu-jupyter/commit/958e6876ece2309482f9f2841a635a9b1f2a1f93 the jupyterlab-git was just added to the Dockerfile, but never to `src/Dockerfile.usefulpackages`.

The first thing that comes to my mind is that the Dockerfile should not be in git, but just generated using the generate script, otherwise you never know which of the versions it contains, and it will not lead to errors like this.
What do you think?

**Comment by ChristophSchranz** [comment]
Good point. `.build/Dockerfile` should maybe not exist. I've decided to put it into a hidden folder to indicate that it is not a good idea to alter it. However, this file is modified by many users and makes it more prone to errors like that you showed. This is because I assume it is generated again.

I'll make some updates today and will remove this file from git. This could also help to recognize that this file is generated.
