### ISSUE TITLE
The Compose file is invalid .. 'devices' was unexpected

### ISSUE THREAD

**Issue by e-velin** [iot-salzburg/gpu-jupyter#46]
Hi,

Thank you for sharing this project.

I get an error when I run " ./start-local.sh -p 8848 ": 

The Compose file './docker-compose.yml' is invalid because:
services.gpu-jupyter.deploy.resources.reservations value Additional properties are not allowed ('devices' was unexpected)
Could you help with this please?

**Comment by ChristophSchranz** [comment]
You're welcome :)  

Requesting resources in `docker-compose` is only available from version 1.28.0 on. [Here](https://docs.docker.com/compose/release-notes/#1280) you can see the changelog. I'm now catching this version problem in a055aab2f0bb599453335ab0ee6cb80c71db53f9 and I've mentioned this problem in the [description](https://github.com/iot-salzburg/gpu-jupyter#start-via-docker-compose).

You can either update your `docker-compose` or just use the direct docker command.

**Comment by e-velin** [comment]
@ChristophSchranz Thank you, I updated my docker-compose, this indeed solved the problem.
