### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by mlashcorp** [iot-salzburg/gpu-jupyter#47]
I'm getting an error when starting the container. Logs below:

[I 2021-02-20 11:07:52.437 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-02-20 11:07:52.441 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-20 11:07:52.441 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-20 11:07:52.441 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-20 11:07:52.441 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-20 11:07:52.441 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-02-20 11:07:52.448 ServerApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2021-02-20 11:07:52.619 ServerApp] jupyter_tabnine | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-20 11:07:52.620 ServerApp] jupyter_tabnine | extension was successfully linked.
[I 2021-02-20 11:07:52.620 ServerApp] nbclassic | extension was successfully linked.
 install dir: /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine
Begin to download TabNine Binary from https://update.tabnine.com/3.2.28/x86_64-unknown-linux-gnu/TabNine
[I 2021-02-20 11:07:52.813 ServerApp] jupyter_tabnine | extension was successfully loaded.
[I 2021-02-20 11:07:52.817 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
[I 2021-02-20 11:07:52.818 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2021-02-20 11:07:52.831 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-20 11:07:52.856 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-20 11:07:52.856 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2021-02-20 11:07:52.856 ServerApp] Jupyter Server 1.4.0 is running at:
[I 2021-02-20 11:07:52.856 ServerApp] http://7f63aa28ed3f:8888/lab
[I 2021-02-20 11:07:52.856 ServerApp]  or http://127.0.0.1:8888/lab
[I 2021-02-20 11:07:52.857 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2018, in launch_browser
    browser = webbrowser.get(self.browser or None)
  File "/opt/conda/lib/python3.8/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 520, in launch_instance
    serverapp.start()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2100, in start
    self.start_app()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2059, in start_app
    self.launch_browser()
  File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2020, in launch_browser
    self.log.warning(_('No web browser found: %s.') % e)
UnboundLocalError: local variable '_' referenced before assignment
Finish download TabNine Binary to /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine/binaries/3.2.28/x86_64-unknown-linux-gnu/TabNine
 Semantic completion enabled.

I'm not sure if the problem is due to the "could not locate runnable browser", or the subsequent unboundlocalerror when trying to log the warning ...

**Comment by mcolladoio** [comment]
Same here, using the master branch of the project, ```docker-compose up``` produces that errors.

**Comment by ChristophSchranz** [comment]
That's an interesting log. I'll check this one. @mlashcorp does it origin from docker-compose?

**Comment by mlashcorp** [comment]
Hey @ChristophSchranz , thanks for replying so quickly. I tried both with docker-compose and with the docker run command. In fact I tried to bypass the runnable browser limitation by trying different combinations of --net="host" and --ip="0.0.0.0" but to no avail.

**Comment by ChristophSchranz** [comment]
I cannot reproduce this error. Here is my log:


Set username to: jovyan
usermod: no changes
Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
Executing the command: jupyter lab
[I 2021-02-17 15:22:56.106 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-02-17 15:22:56.109 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-17 15:22:56.109 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-17 15:22:56.109 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-17 15:22:56.109 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-17 15:22:56.109 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-02-17 15:22:56.115 ServerApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2021-02-17 15:22:56.237 ServerApp] jupyter_tabnine | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-17 15:22:56.238 ServerApp] jupyter_tabnine | extension was successfully linked.
[I 2021-02-17 15:22:56.238 ServerApp] nbclassic | extension was successfully linked.
 install dir: /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine
Begin to download TabNine Binary from https://update.tabnine.com/3.2.28/x86_64-unknown-linux-gnu/TabNine
[I 2021-02-17 15:22:56.387 ServerApp] jupyter_tabnine | extension was successfully loaded.
[I 2021-02-17 15:22:56.391 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
[I 2021-02-17 15:22:56.391 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2021-02-17 15:22:56.404 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-17 15:22:56.418 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-17 15:22:56.418 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2021-02-17 15:22:56.418 ServerApp] Jupyter Server 1.3.0 is running at:
[I 2021-02-17 15:22:56.419 ServerApp] http://6e9a0eb692ca:8888/lab
[I 2021-02-17 15:22:56.419 ServerApp]  or http://127.0.0.1:8888/lab
[I 2021-02-17 15:22:56.419 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2021-02-17 15:22:56.421 ServerApp] No web browser found: could not locate runnable browser.
Finish download TabNine Binary to /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine/binaries/3.2.28/x86_64-unknown-linux-gnu/TabNine
 Semantic completion enabled.
[C 2021-02-22 10:14:59.381 ServerApp] received signal 15, stopping
[I 2021-02-22 10:14:59.382 ServerApp] Shutting down 0 kernels
Set username to: jovyan
usermod: no changes
Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
Executing the command: jupyter lab
[I 2021-02-22 10:15:03.461 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-02-22 10:15:03.464 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 10:15:03.464 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 10:15:03.464 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 10:15:03.464 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-22 10:15:03.464 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-02-22 10:15:03.597 ServerApp] jupyter_tabnine | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-22 10:15:03.597 ServerApp] jupyter_tabnine | extension was successfully linked.
[I 2021-02-22 10:15:03.597 ServerApp] nbclassic | extension was successfully linked.
 install dir: /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine
TabNine binary already exists in /home/jovyan/.local/lib/python3.8/site-packages/jupyter_tabnine/binaries/3.3.59/x86_64-unknown-linux-gnu/TabNine ignore downloading
 Semantic completion enabled.
[I 2021-02-22 10:15:04.721 ServerApp] jupyter_tabnine | extension was successfully loaded.
[I 2021-02-22 10:15:04.722 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
[I 2021-02-22 10:15:04.722 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2021-02-22 10:15:04.726 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-22 10:15:04.730 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-22 10:15:04.730 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2021-02-22 10:15:04.730 ServerApp] Jupyter Server 1.3.0 is running at:
[I 2021-02-22 10:15:04.730 ServerApp] http://6e9a0eb692ca:8888/lab
[I 2021-02-22 10:15:04.730 ServerApp]  or http://127.0.0.1:8888/lab
[I 2021-02-22 10:15:04.730 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
**[W 2021-02-22 10:15:04.733 ServerApp] No web browser found: could not locate runnable browser.**
[I 2021-02-22 11:03:32.195 ServerApp] 302 GET / (172.17.0.1) 0.41ms
[I 2021-02-22 11:03:32.208 LabApp] 302 GET /lab? (172.17.0.1) 0.57ms
[I 2021-02-22 11:03:33.991 ServerApp] 302 POST /login?next=%2Flab%3F (172.17.0.1) 0.74ms
[W 2021-02-22 11:03:36.326 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.333 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.354 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.358 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.367 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.375 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.385 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.392 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.420 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.424 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.560 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.565 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.634 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.653 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.661 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.672 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.698 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.806 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.894 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.900 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.921 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.925 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.933 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.940 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.951 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.958 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.989 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:36.993 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.108 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.113 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.171 ServerApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.187 ServerApp] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.194 ServerApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.204 ServerApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.225 ServerApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-02-22 11:03:37.316 ServerApp] Config option `template_path` not recognized by `LenvsSlidesExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
**[I 2021-02-22 11:03:37.336 LabApp] Build is up to date**


Here it seems that Jupyter can't find a runnable browser, but doesn't crash. I can open and use it in a Browser.

**Comment by ChristophSchranz** [comment]
Do you also have this problem when using a specific tag as mentioned in the quickstart section?

**Comment by ChristophSchranz** [comment]
Okay I have replicated the issue, and found it as issue here: https://github.com/jupyter-server/jupyter_server/issues/422

**Comment by ChristophSchranz** [comment]
There seems to be a rollback from Jupyter docker-stacks as well, see this commit: https://github.com/jupyter/docker-stacks/commit/6ae8512231f8420a73449b1dd99f532f518630f0

Later, they only partially moved to 3.0

I'll also roll back, until they have not fixed it.

**Comment by ChristophSchranz** [comment]
Okay I figured out the issue:  
In the base-image of docker-stack a file was renamed to be suited for Jupyterlab 3.0.
However, when building the whole Dockerfile, a Jupyterlab 3.0 dependency is installed that is cached for version 2.0 and therfore lead to a incompatibility. (see e.g. [this](https://github.com/jupyter/docker-stacks/issues/1240))

Long story short, force a rebuild of the image using:
```
docker build --no-cache -t gpu-jupyter .build/ 
```

I'll update the images such this issue won't happen for them.

**Comment by ChristophSchranz** [comment]
Solved with commit 6a9a401abfd5764220b3f3ab927827c4abb99bae

The updated images are currently building and pushed.

Please reopen if your issue is still present.
