### ISSUE TITLE
Ignoring visible gpu devices with compute capability 3.0. The minimum required Cuda capability is 3.5

### ISSUE THREAD

**Issue by e-velin** [iot-salzburg/gpu-jupyter#49]
Hi, 

I know it sounds bad, but I have just realised that the pc I'm trying to set up this system on has really old gpus, with cuda capability 3.0. Tensorflow supports >3.5. But theoretically it is possible to use it with cc 3.0 too by building tensorflow or disabling xla (?). However, I would like to use these gpus with this setup (jupyter + docker + gpu), do you have any idea how to solve this/whether is it possible to solve this? I'm still getting to know using docker. 
I managed to launch jupyter lab following your tutorial on medium.com and only then I realised that the gpus were not detected.

**Comment by ChristophSchranz** [comment]
The important part is to find the most current cuda version that is supported by your gpu, i.e., where this command detects your gpu:

```
docker run --gpus all nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 
```

A list of cuda tags is [here](https://hub.docker.com/r/nvidia/cuda/tags?page=1&ordering=last_updated)

Afterwards, just replace the current cuda version with the one that is supported by your gpu in https://github.com/iot-salzburg/gpu-jupyter/blob/6a9a401abfd5764220b3f3ab927827c4abb99bae/src/Dockerfile.header#L3

Then, generate the Dockerfile and build it as described in the README.

Hope this works for you!
