### ISSUE TITLE
Fastai as one of default packages

### ISSUE THREAD

**Issue by szperajacyzolw** [iot-salzburg/gpu-jupyter#53]
Hi

It would be great if you include fastai in your image.

Best regards, Jakub.

**Comment by ChristophSchranz** [comment]
Hi @szperajacyzolw 
Adding fastai with the command `conda install -c fastchan fastai` will increase the image size by 1.24 GB. This is too high to add this to this project, given that only a fraction of users are using this framework.

However, everyone who uses it is encouraged to install fastai by appending the installation line in `src/Dockerfile.gpulibs`.
