### ISSUE TITLE
TensorFlow does not detect GPU

### ISSUE THREAD

**Issue by dsmanl** [iot-salzburg/gpu-jupyter#58]
Dear all, first of all thanks a lot for your efforts! I am currently facing the problem that `torch` as well as `numba` successfully detect `cuda` or the gpu but `tensorflow` does not. 

I have an Ubuntu "20.04.2 LTS (Focal Fossa)" machine with a Quadro RTX 6000 (Driver 460.56 and CUDA version 11.2). I am running the `cschranz/gpu-jupyter:latest` image with the digest `sha256:5f0f9ee643573f6255e09242afbd107d339b089c1d3a1be2a66bd1b5b59ef443`.

The base setup seems to work fine as I can run `nvidia-smi` from the terminal inside of the image and get reasonable results:

![grafik](https://user-images.githubusercontent.com/67360039/112115639-b6fa4e00-8bb9-11eb-973e-4e202f8064aa.png)

Running the `PyTorch` check returns `True`:
```python
import torch
torch.cuda.is_available()
```

Running the `numba` check returns `True` as well:
```python
from numba import cuda
cuda.is_available()
```

In contrast to this the `TensorFlow` check returns `False`:
```python
import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
```

The output of 
```python
import tensorflow as tf
from tensorflow.python.client import device_lib
print(tf.config.list_physical_devices('XLA_GPU'))
device_lib.list_local_devices()
```
is
```
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 10269939690289433299,
 name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 6286114861605125503
 physical_device_desc: "device: XLA_CPU device",
 name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 2585380967679947376
 physical_device_desc: "device: XLA_GPU device"]
```

Do you have any ideas with regard to that issue?

Thanks a lot!

**Comment by KittyMcMitty** [comment]
Can confirm same issue with RTX 3070. From the terminal output from the container it looks like tensorflow can't find a required library.

![image](https://user-images.githubusercontent.com/59396640/112884828-dfa5aa80-90c7-11eb-8219-80b0cf2887a1.png)

![image](https://user-images.githubusercontent.com/59396640/112884889-f6e49800-90c7-11eb-9f3f-f9da26bd3b06.png)

**Comment by KittyMcMitty** [comment]
Found a solution. The instructions in the README for this repo recommend running the command `docker run --gpus all -d -it -p 8848:8888 -v $(pwd)/data:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root cschranz/gpu-jupyter:v1.3_cuda-10.2_ubuntu-18.04_python-only`. This will run a CUDA 10.2 container, but TensorFlow 2.3 requires CUDA 10.1 not 10.2.

The solution is to use the `v1.3_cuda-10.1_ubuntu-18.04_python-only` tag instead. This results in a TensorFlow installation that will make use of the GPU.

![image](https://user-images.githubusercontent.com/59396640/112896809-c7895780-90d6-11eb-9a22-0657c4797ade.png)

Note here that the CUDA version reported by nvidia-smi represents the max supported CUDA version for the driver. This is the output from the CUDA 10.1 container.

**Comment by ChristophSchranz** [comment]
Thanks for reporting this bug and finding a solution!

Yes, the CUDA base-image has to be reverted back to version 10.1. I'll revert and test it.

**Comment by dsmanl** [comment]
@ChristophSchranz and @KittyMcMitty many thanks for finding a fix for the issue!

**Comment by ChristophSchranz** [comment]
The commit 3ea76d001bfbdae91a662481902186e6b35adb99 should have resolved this issue.

Please reopen if not.
