### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by congdaoduy298** [iot-salzburg/gpu-jupyter#67]
First of all, thank you for your repository. And may I ask you why I can not create a new notebook. I tried a lot of answer from google but nothing seem happens. I tried to pass many params to overcome that errors like `-e GRANT_SUDO=yes` `--user root NB_UID=$(id -u)` `-e NB_GID=$(id -g)` but I still can not create new notebook. 
Here is my full command:
`sudo docker run -it --rm -d -p 9012:8888 -v $(pwd):/home/jovyan/work/ -e NB_UID=$(id -u) -e NB_GID=$(id -g) -e GRANT_SUDO=yes --user root cschranz/gpu-jupyter:v1.4_cuda-11.0_ubuntu-20.04_python-only`. 
I go to docker container and here is the error:
**PermissionError: [Errno 13] Permission denied: '/home/jovyan/work/Cong/wsi_ai/.ipynb_checkpoints/Untitled-checkpoint.ipynb'**
Thanks for any helps
![Screenshot from 2021-10-18 20-21-41](https://user-images.githubusercontent.com/44945898/137764851-2df3b4bd-dc30-4278-9d77-e42fa620bbc0.png)
.

**Comment by ChristophSchranz** [comment]
Closing as there were no contributions for a while. Please reopen, if the error still occurs.
