### ISSUE TITLE
Cant access jupyter on EC2

### ISSUE THREAD

**Issue by eskamoah** [iot-salzburg/gpu-jupyter#7]
I went through the whole process of setting everything up on following https://medium.com/@christoph.schranz/set-up-your-own-gpu-based-jupyterlab-e0d45fcacf43

Everything installs just fine and it seems to start the docker container and jupyter lab however, I cannot seem to connect to it. See log file below

gpu-jupyter_1  | Set username to: jovyan
gpu-jupyter_1  | usermod: no changes
gpu-jupyter_1  | Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
gpu-jupyter_1  | Executing the command: jupyter lab
gpu-jupyter_1  | [I 20:43:07.743 LabApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
gpu-jupyter_1  | [I 20:43:08.007 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
gpu-jupyter_1  |  install dir: /opt/conda/lib/python3.7/site-packages/jupyter_tabnine
gpu-jupyter_1  | Begin to download TabNine Binary from https://update.tabnine.com/2.3.4/x86_64-unknown-linux-gnu/TabNine
gpu-jupyter_1  | Finish download TabNine Binary to /opt/conda/lib/python3.7/site-packages/jupyter_tabnine/binaries/2.3.4/x86_64-unknown-linux-gnu/TabNine
gpu-jupyter_1  | [I 20:43:08.549 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
gpu-jupyter_1  | [I 20:43:08.549 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
gpu-jupyter_1  | [I 20:43:08.551 LabApp] Serving notebooks from local directory: /home/jovyan
gpu-jupyter_1  | [I 20:43:08.551 LabApp] The Jupyter Notebook is running at:
gpu-jupyter_1  | [I 20:43:08.551 LabApp] http://f421fa7971ac:8888/
gpu-jupyter_1  | [I 20:43:08.551 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
gpu-jupyter_1  | [C 20:44:15.403 LabApp] received signal 15, stopping
gpu-jupyter_1  | [I 20:44:15.404 LabApp] Shutting down 0 kernels
gpu-jupyter_1  | Set username to: jovyan
gpu-jupyter_1  | usermod: no changes
gpu-jupyter_1  | Granting jovyan sudo access and appending /opt/conda/bin to sudo PATH
gpu-jupyter_1  | Executing the command: jupyter lab
gpu-jupyter_1  | [I 20:46:54.775 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
gpu-jupyter_1  |  install dir: /opt/conda/lib/python3.7/site-packages/jupyter_tabnine
gpu-jupyter_1  | TabNine binary already exists in /opt/conda/lib/python3.7/site-packages/jupyter_tabnine/binaries/2.3.4/x86_64-unknown-linux-gnu/TabNine ignore downloading
gpu-jupyter_1  | [I 20:46:55.134 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.7/site-packages/jupyterlab
gpu-jupyter_1  | [I 20:46:55.134 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
gpu-jupyter_1  | [I 20:46:55.136 LabApp] Serving notebooks from local directory: /home/jovyan
gpu-jupyter_1  | [I 20:46:55.136 LabApp] The Jupyter Notebook is running at:
gpu-jupyter_1  | [I 20:46:55.136 LabApp] http://f421fa7971ac:8888/
gpu-jupyter_1  | [I 20:46:55.136 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Also when I try to telnet to see if the port is open showing anything I get back
telnet localhost 8888
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

Also doesnt work if I use the AWS address either. 

Is docker not passing the jupyter notebook through to the port outside the container? How would I fix this.

If I run jupyter notebook or jupyter lab without the docker it works just fine.

**Comment by ChristophSchranz** [comment]
Hi @eskamoah ,
Have you exposed the port 8888 explicitly (with the `-p [port] param)? If exposed to another port, the logs within a container can be missleading sometimes.
Are you trying to telnet localhost:port within the same node on AWS? Otherwise, a static URL has to be created in AWS.
If this doesn't help, I would suggest to run the steps in the startup script line by line.

**Comment by ChristophSchranz** [comment]
Closing, as AWS is not part of this project and there is no response for 7 days.

**Comment by eskamoah** [comment]
@ChristophSchranz hey sorry, I did use the -p flag and put in port both 8888 and 8888:8888 but neither worked. Is there a way around using a static IP? it doesnt seem to be necessary since I will direct my address bar to whatever IP AWS starts up on

**Comment by eskamoah** [comment]
I tried Telnet from the AWS machine I was logged into that was running the jupyter notebook. When jupyter notebook is running successfully telnet localhost 8888 works but when i do it through this gpu docker it doesnt.

**Comment by ChristophSchranz** [comment]
Maybe [this](https://www.youtube.com/watch?v=ZdxCW1zaJik) helps you.
