### ISSUE TITLE
Memory limited to 3.2Gig

### ISSUE THREAD

**Issue by SamueLacombe** [iot-salzburg/gpu-jupyter#76]
Hello,

I was really glad to find this docker image. Thanks for your hardwork!

I'm having an issue as I'm limited to 3.5 gig at all time even though there is over 100 Gig available. I searched on the internet and tried to change the config file to set NotebookApp.max_buffer_size = 26843545600  (25gig) but to no avail.

All the information on the internet seem to be related to Google Colab (outside of the NotebookApp.max_buffer_size).. and I have no clue how to remove that limitation.

Thank you,
Samuel

**Comment by mathematicalmichael** [comment]
I'm assuming you mean memory as in RAM?

how are you launching the image? if you're using a jupyterhub for instance, memory limits are configured there regardless of which container is launched.

**Comment by SamueLacombe** [comment]
Hello,

You are correct, when I say memory I'm referring to RAM.

My current set-up is running using docker-compose on my own ubuntu server. We haven't put any restriction on the RAM in the docker set-up. 

Honestly, I'm prety sure the issue is within the config of Jupyter, but I have tried everything aivalable on the internet and nothing avail. 

P.S: I have identified the error, because the Kernel die everytimes I reach around 3.5Gig.

Thanks for the quick reply!

Best regards,
Samuel

**Comment by ChristophSchranz** [comment]
Hi @SamueLacombe ,
can you post the result of `docker info`, `docker inspect gpu-jupyter` and your docker configs/daemon in `etc/docker/` or `/mnt/c/Users/user/.docker/`?

How high is your memory limit in other containers?
Do you have the same problem if you start the container with docker (without compose)?
See this [post](https://docs.docker.com/config/containers/resource_constraints/) and search for docker configuration.

**Comment by SamueLacombe** [comment]
Hello @ChristophSchranz 

So I made a little mistake. The max RAM when the Kernel crash is 3.2G and not 3.5G.

We have only tried Docker, not with Docker Compose.

The other Dockers on the server are not limited in memory and there is plenty of free memory. The server is a threadripper with over 100G of RAM.


here are the ingo you asked:

`docker info


Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 87
  Running: 20
  Paused: 0
  Stopped: 67
 Images: 779
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-99-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 125.7GiB
 Name: vgrdocker3
 ID: MKE3:OELT:RMLI:7AMK:R64B:2OGY:WUX4:AKTJ:26TR:BUMZ:5DRA:NUVX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support



docker inspect gpu-jupyter


[
    {
        "Id": "sha256:ee3bf5d6867e51ffb4cc2c1b10e446497e48cf3028753b7e70938cea870b0624",
        "RepoTags": [
            "gpu-jupyter:latest",
            "gpu-jupyter_gpu-jupyter:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:e8602ccf73af3e5363422d835a52b0eb7fa543c559abb957828647bb38458635",
        "Comment": "",
        "Created": "2022-03-09T21:37:49.729713139Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "1000",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NVARCH=x86_64",
                "NVIDIA_REQUIRE_CUDA=cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450",
                "NV_CUDA_CUDART_VERSION=11.2.152-1",
                "NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-2",
                "NV_ML_REPO_ENABLED=1",
                "NV_ML_REPO_URL=https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64",
                "CUDA_VERSION=11.2.2",
                "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "NV_CUDA_LIB_VERSION=11.2.2-1",
                "NV_NVTX_VERSION=11.2.152-1",
                "NV_LIBNPP_VERSION=11.3.2.152-1",
                "NV_LIBNPP_PACKAGE=libnpp-11-2=11.3.2.152-1",
                "NV_LIBCUSPARSE_VERSION=11.4.1.1152-1",
                "NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-2",
                "NV_LIBCUBLAS_VERSION=11.4.1.1043-1",
                "NV_LIBCUBLAS_PACKAGE=libcublas-11-2=11.4.1.1043-1",
                "NV_LIBNCCL_PACKAGE_NAME=libnccl2",
                "NV_LIBNCCL_PACKAGE_VERSION=2.8.4-1",
                "NCCL_VERSION=2.8.4-1",
                "NV_LIBNCCL_PACKAGE=libnccl2=2.8.4-1+cuda11.2",
                "NV_CUDNN_VERSION=8.1.1.33",
                "NV_CUDNN_PACKAGE=libcudnn8=8.1.1.33-1+cuda11.2",
                "NV_CUDNN_PACKAGE_NAME=libcudnn8",
                "DEBIAN_FRONTEND=noninteractive",
                "CONDA_DIR=/opt/conda",
                "SHELL=/bin/bash",
                "NB_USER=jovyan",
                "NB_UID=1000",
                "NB_GID=100",
                "LC_ALL=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US.UTF-8",
                "HOME=/home/jovyan",
                "XDG_CACHE_HOME=/home/jovyan/.cache/",
                "JULIA_DEPOT_PATH=/opt/julia",
                "JULIA_PKGDIR=/opt/julia",
                "JULIA_VERSION=1.7.1"
            ],
            "Cmd": [
                "/bin/bash",
                "-o",
                "pipefail",
                "-c",
                "#(nop) COPY file:c69ac097f4dbd292626d206ab1615e506aa3c9ea18d3933ec4a0f3742a11ff63 in /etc/jupyter/ "
            ],
            "Image": "sha256:e8602ccf73af3e5363422d835a52b0eb7fa543c559abb957828647bb38458635",
            "Volumes": null,
            "WorkingDir": "/home/jovyan",
            "Entrypoint": [
                "tini",
                "-g",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "authors": "Christoph Schranz <removed>, Mathematical Michael <removed>",
                "com.nvidia.cudnn.version": "8.1.1.33",
                "maintainer": "Christoph Schranz <removed>"
            },
            "Shell": [
                "/bin/bash",
                "-o",
                "pipefail",
                "-c"
            ]
        },
        "DockerVersion": "20.10.12",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "1000",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8888/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NVARCH=x86_64",
                "NVIDIA_REQUIRE_CUDA=cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450",
                "NV_CUDA_CUDART_VERSION=11.2.152-1",
                "NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-2",
                "NV_ML_REPO_ENABLED=1",
                "NV_ML_REPO_URL=https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64",
                "CUDA_VERSION=11.2.2",
                "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "NV_CUDA_LIB_VERSION=11.2.2-1",
                "NV_NVTX_VERSION=11.2.152-1",
                "NV_LIBNPP_VERSION=11.3.2.152-1",
                "NV_LIBNPP_PACKAGE=libnpp-11-2=11.3.2.152-1",
                "NV_LIBCUSPARSE_VERSION=11.4.1.1152-1",
                "NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-2",
                "NV_LIBCUBLAS_VERSION=11.4.1.1043-1",
                "NV_LIBCUBLAS_PACKAGE=libcublas-11-2=11.4.1.1043-1",
                "NV_LIBNCCL_PACKAGE_NAME=libnccl2",
                "NV_LIBNCCL_PACKAGE_VERSION=2.8.4-1",
                "NCCL_VERSION=2.8.4-1",
                "NV_LIBNCCL_PACKAGE=libnccl2=2.8.4-1+cuda11.2",
                "NV_CUDNN_VERSION=8.1.1.33",
                "NV_CUDNN_PACKAGE=libcudnn8=8.1.1.33-1+cuda11.2",
                "NV_CUDNN_PACKAGE_NAME=libcudnn8",
                "DEBIAN_FRONTEND=noninteractive",
                "CONDA_DIR=/opt/conda",
                "SHELL=/bin/bash",
                "NB_USER=jovyan",
                "NB_UID=1000",
                "NB_GID=100",
                "LC_ALL=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US.UTF-8",
                "HOME=/home/jovyan",
                "XDG_CACHE_HOME=/home/jovyan/.cache/",
                "JULIA_DEPOT_PATH=/opt/julia",
                "JULIA_PKGDIR=/opt/julia",
                "JULIA_VERSION=1.7.1"
            ],
            "Cmd": [
                "start-notebook.sh"
            ],
            "Image": "sha256:e8602ccf73af3e5363422d835a52b0eb7fa543c559abb957828647bb38458635",
            "Volumes": null,
            "WorkingDir": "/home/jovyan",
            "Entrypoint": [
                "tini",
                "-g",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "authors": "Christoph Schranz <removed>, Mathematical Michael <removed>",
                "com.nvidia.cudnn.version": "8.1.1.33",
                "maintainer": "Christoph Schranz <removed>"
            },
            "Shell": [
                "/bin/bash",
                "-o",
                "pipefail",
                "-c"
            ]
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 17856278374,
        "VirtualSize": 17856278374,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a5aa232a8446348d335b57673cc3ed3ac79245ac52024208ba79ac20402490a2/diff:/var/lib/docker/overlay2/fa9ec9ba82a082e9dd8e10d85c2f1dbf350c2186c3db5a9f9a345782f64b9a15/diff:/var/lib/docker/overlay2/c26360c460e454787f549f7c44f6976019a9230a48733c5b3a5be3e0a1b5de1d/diff:/var/lib/docker/overlay2/520947b55fb1af40d0909dcde3f19bea0bcb3597d79bd8dc099b4fe0a30a25f0/diff:/var/lib/docker/overlay2/25be89eebf50e6788034687790e1228d3ac043a941b232f6c5a5ff12dbe0a7fa/diff:/var/lib/docker/overlay2/8184914d7d5696b0c5679d49d321c9761ea326762b400dd321dfc20bfce29ed1/diff:/var/lib/docker/overlay2/618aac880a16da540ec75b22a37df0a2627ffdb1c58c32527360c66e3d0501a1/diff:/var/lib/docker/overlay2/0dcb15a6ecee713dc030a3be84e935b77949bdfcc493d5831bc0896f80df1bff/diff:/var/lib/docker/overlay2/cf6da702d0203663a224a31edcba76e2f456769b2b1c2625636e28c4a1805fca/diff:/var/lib/docker/overlay2/a4c955bf65c330aa5ce9ec360f5bebdb3e5702a23593a262d5ef384d4e4777ef/diff:/var/lib/docker/overlay2/1629cf18ad3d387cedf8d5c8f33eda79988506b89327282f4576d97e3f0f90e8/diff:/var/lib/docker/overlay2/4fe5654331d640b3f01297694b85c6f80e2e2a10426bc0100752b3af6ab399a9/diff:/var/lib/docker/overlay2/506b6203367f1050e9cfa0a85741fc32f3edfbbd31b03412beaf8d435f0a9812/diff:/var/lib/docker/overlay2/4be67efb53b7cd3e3dee7eadba656c373b0b292651aee5b1325fc57c15c07dcc/diff:/var/lib/docker/overlay2/5898c08d65e6cb1330f9d341abb2eb6e50668977e2029bac860ff510b08fad4c/diff:/var/lib/docker/overlay2/8581d831d634373c29b28936402213213697b855a2abc18393eb69fba0552c65/diff:/var/lib/docker/overlay2/2dede00673496e05f4bd221bf1cdd395a24c25bd94519c06373430e04b65749a/diff:/var/lib/docker/overlay2/e376d60cac15a17a4b4805858d0c43f5d2e7d71b51990f8574cb1de52cd60e85/diff:/var/lib/docker/overlay2/668ddb0b59249ae99bec64f0d30c2f534fa2c184b5f1e05a2fdfabe975f4e156/diff:/var/lib/docker/overlay2/ec5ca294f730687ee387cda5a48d0e309e95f207ef1b46dd1c06e9fd6bb46255/diff:/var/lib/docker/overlay2/1f97654e7f6784858b1cb07f1dadbc4bd9129aa60053bd9e31b85433d657d613/diff:/var/lib/docker/overlay2/940ccc111a9e5ab9f30b5a08a15f52dbe58817f5593d22ca6f6e81b9641db80a/diff:/var/lib/docker/overlay2/73f58f6482ad87e48106974eea2c437d968db8c2e0a7c50e59c73d75d937f512/diff:/var/lib/docker/overlay2/1f2dce92d3354e740ac8952d6ea8705e9c6c1f5831c04ac74d24ecd1f6065d73/diff:/var/lib/docker/overlay2/9eb7660b7caf88812229b536ebc28a7b747736208c936c7d8252d3f8371c0eb9/diff:/var/lib/docker/overlay2/63f992aab536333bc057e1cfcbce8be2d3e4186603adb4923ba06dabbbf0d93b/diff:/var/lib/docker/overlay2/56e3759f54657d31f1e886f7c12aec7348e6cf30dc41fd7a97e6f4c423230d7c/diff:/var/lib/docker/overlay2/5d7f203a23eb84417998c9c63f90cc79d3df6c57aab54e3eb31c9c6c6193c7ff/diff:/var/lib/docker/overlay2/1024de9c2f76cdaf23534c89c64b552fd2125ece9795b73b68946aeaae567e73/diff:/var/lib/docker/overlay2/9de57e5c701ffaea43b56154440908fa0c941483dbd7d22e0c0805f0d4efe2e2/diff:/var/lib/docker/overlay2/2acec6cee112238f36d534b2635487c9b6b631f125692629a92237a6b8d6c946/diff:/var/lib/docker/overlay2/c797bb43b341b09812c2edb7368b7155677898941ab15cccd614570db88621bb/diff:/var/lib/docker/overlay2/a0138983066dfc53fab120fb45ff29f32e09d40227e3c428dd78944be0de09be/diff:/var/lib/docker/overlay2/9705ee1c5ac5bba5f877a3aafb94f83dc74ba58fbbb9a3921237322e972c2b31/diff:/var/lib/docker/overlay2/7509f423cd47f52d81c96a7f49d5d239d883990376faa5033e9a864408b0eab1/diff:/var/lib/docker/overlay2/70e6a6ce6a7c60e9141fc239e784e71fcc1e4c2f7c08b0231059b89b9ed5e03a/diff:/var/lib/docker/overlay2/2806c086843fd818f9e903d9c5f63b46a002013bea67b1d55ec991cb6194613f/diff:/var/lib/docker/overlay2/030dfd55ebe32b84b7c6b5c4e73253b5547dae4eceb829d8cb568b9c74455b69/diff:/var/lib/docker/overlay2/b2a56f175365c38750038be76b32478726eda5b0dafea64c0346548181b9e862/diff:/var/lib/docker/overlay2/d09fd19cdf29a2e0eb48d69b2041af4dcec4e026313c5e735445db36368cadc3/diff:/var/lib/docker/overlay2/a145b0935222f946c19082606009872a440a5c384a0d1efeb85b1c481c217717/diff:/var/lib/docker/overlay2/f306234e5ac66ba97b007df92980bbc05a6477a293089bf61299382280c85871/diff:/var/lib/docker/overlay2/8f5b414b7496f1d4896e9148a1cd55a3dc44fbb87cd7804ab2d399bb6d66cc01/diff:/var/lib/docker/overlay2/abebe1f2936cd88e111c9d799038ce245be6d7108ca4133ca12112074e77576d/diff:/var/lib/docker/overlay2/307504e77e79184814a2409701c535b06b20937df25a7cccf3d8ca25528fead6/diff:/var/lib/docker/overlay2/3ab35fa52ccc7f2f8cb4c250a6240bbef20c32a95a0941792707ffadabe96ca6/diff:/var/lib/docker/overlay2/2fa3bf3f182bd4d33de0d9cf171c2eee73a5d3ae30fd7d40e2bb49894a19c5fc/diff",
                "MergedDir": "/var/lib/docker/overlay2/5ff90aaa66599b4e5ab38580cedf9cd365ca5e5eeeb8615a2ef219bedecdc76e/merged",
                "UpperDir": "/var/lib/docker/overlay2/5ff90aaa66599b4e5ab38580cedf9cd365ca5e5eeeb8615a2ef219bedecdc76e/diff",
                "WorkDir": "/var/lib/docker/overlay2/5ff90aaa66599b4e5ab38580cedf9cd365ca5e5eeeb8615a2ef219bedecdc76e/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:9f54eef412758095c8079ac465d494a2872e02e90bf1fb5f12a1641c0d1bb78b",
                "sha256:1bd360619c259a00adf0ed5fec7c442c460f4a71f1790d4aee30146ef4f6e433",
                "sha256:6e52c6a02e59fb640733df5021d17e103afdff13fcbab8366338d5959cfcb220",
                "sha256:ce06dacd3d96432255317713b7d13fbab7d8c7d55e1e45c1398ac45f030cec10",
                "sha256:4f8af6e687479a548226b3f89a2faa295f933ec63f84b056c2397c08860f4c8e",
                "sha256:2885ff9ed5c79c51206c47b8e7ca873908f0b1499bad552bcadfea93e481ba4f",
                "sha256:16266fe134aca2d4837a5404129c6eba15e200d05ebc1361093455b74d2e9bde",
                "sha256:34c34b9955a837fdc64127bdea59aabe830ec55542cda2dc5f5fa6f3f959ff57",
                "sha256:d449de4ee4e1b12e9d668dc33f82757fa69ca9f20f4095f3ab2b35b78245ad62",
                "sha256:ce57c81a192b1b6e90baf2525ccfeab0b05dfd41a8e3c09adc60a99f2cb8cb37",
                "sha256:79699e61029dc677da99392b548b0365abe246c1eba13ee4fc7497c8a020decd",
                "sha256:79699e61029dc677da99392b548b0365abe246c1eba13ee4fc7497c8a020decd",
                "sha256:adca2459f872e294b764a739bba8aac08434e33dbf029be17997a8393bc18a7d",
                "sha256:4782dceab095aa4d004517104c451f72b2571a08d4510d3b3ae7d1005468411a",
                "sha256:9038957107a359a8b8618cbe3a39e16ffb1789b416b858c5e15bec79d7d4bcc5",
                "sha256:f2cd558013047975f12c990d97f94080e2d44ffbc075111c4f8e1d0114b75895",
                "sha256:c8f578cf1188ec05821c91002df5028c602bb832d4b137e558e9c9ee86570dcd",
                "sha256:8be9501d39890d7b34b369e4675230951f9ce27164ee1013317a1ba649722d6e",
                "sha256:35493781d7ef0be40f9e95a3a7997066823a2296ad2cd47d8a9646afc1bc9462",
                "sha256:5519e8f8ed3b7e1c4c741ce9202a373dc70c70db6cfe47ea2e545fdeb3558ea7",
                "sha256:3c40dbfd826d8fdaf34a2ca63cf1454d09588f0584da3611e2bc07516187378d",
                "sha256:6611fb3daed181c312a04c81f5abb545e5d5dc90e0076c9e7ebbbcf53f8e23ff",
                "sha256:e735016f21330ad85a39d48f669e3c0e54556f3496069c87fe912a94af2f1d68",
                "sha256:466f3ed8131156f89f57adbb166113f57d057e856f9c893fca739c95ce617f81",
                "sha256:a8e5f4c6b31f5c61490fddfc4c2ad110f1f75ca304f9989ce5ed90cfe9dc925c",
                "sha256:4aee60d6233de2dd090be659d4a7a99e27f4396891b04f750b901b1ddb8c9bc2",
                "sha256:c046964ebadd13f26043dae762f362033d3e1fcda528c749891827566dfaa457",
                "sha256:bff421b778dc2020aa1de213d9ca31548512e6e9b23bd816ccfae25e4d83dcd5",
                "sha256:5eaf75d49b7f25202c6798ee1abab3ba67437fca4bde7937938af1b3cda37b7f",
                "sha256:aee8de7d913ceaa45d3fd50ffb33e51b06478e5819476e7f1c00c24b0b4f5695",
                "sha256:6c1c7158e86ab3e7b70a79138198c10382adbfa7003972e7e9b2868e4434732a",
                "sha256:ddc34dbb28cdc502cadd1eb0a19db0adf34c5a41ef5702088a9d1be570087585",
                "sha256:d14aca73efc019b18df695c39b73564f857c25b2d8fc32e7cac8ad8943632e7c",
                "sha256:31dc3ccea47297ab7ba3ad420dbbb2338f5cb8fe4251adff7ac6510efb5cf186",
                "sha256:90c138b87796025cdd7f9c995ba155c74d18ba55cd6248ef3217d02d7aba1e49",
                "sha256:0002fb2ac1e5f467708e5954549b600ad84518a5863a5c5dea14c3c050c5dd3f",
                "sha256:dcf70772f3c632f6e4698ed7cc33a661490754a2248986db5142f64dae70a25a",
                "sha256:490f800846e3b118016f7b6942a4db54762f20efe79818e425de377774f79982",
                "sha256:9609bdc3862a661e31db2986d300d7f1f8dd1c55de4edb6c488076aa5306ce4b",
                "sha256:740a99c6f01349048d0d83ecbb0db14921147de335779eaebb968d709bdce8f9",
                "sha256:26295cfdff0bc865ba8aaeb3a323cc3447437361c931270cb89d5ad54e46ed74",
                "sha256:84e1a0db8115c6bfe9c61949134c09f33ecb39aeb531e98c108bb842f93a3000",
                "sha256:362d4f8a2d01bf914839375d5effa97c42581e1159273e67c23b129227e5a3a9",
                "sha256:2044c52f353fdb6a97e1ca649e740175dc77d563187b29f5fabf5f9a47008432",
                "sha256:835626b622fd38f571a7e8b80fe4b76e3b5a658ca14e7098d5265d2511af2835",
                "sha256:9e1cb7a8088dedb941927fc7abd27531fd198c18665f2141d750c51c642233ae",
                "sha256:b72568ba6f91f737ef9eba2bbd0725229a24c03e677fe2d9959fc76efe44f06e",
                "sha256:ed903d8f18b3c596ed85f875368a49b5ed3e96588db3105100ed0b6db9379f54"
            ]
        },
        "Metadata": {
            "LastTagTime": "2022-03-10T08:10:01.190829166-05:00"
        }
    }
]


cat /etc/docker/daemon.json


{
  "dns": ["<internal dns server ip>","<internal dns server ip>"],
  "dns-search": ["domain.internal"],
  "runtimes": {
    "nvidia": {
      "path": "nvidia-container-runtime",
      "runtimeArgs": []
    }
  }
}`

**Comment by ChristophSchranz** [comment]
Unfortunately, it is not clear to me why this happens.

Have you tried an older tag, e.g. `docker pull cschranz/gpu-jupyter:v1.4_cuda-11.0_ubuntu-18.04_slim`?

**Comment by SamueLacombe** [comment]
Hello, just to give more information.

I did some more testing to make sure this was not just random and anytime I use the latest version I get the issue with the RAM imitation. Anytime I run with `docker pull cschranz/gpu-jupyter:v1.4_cuda-11.0_ubuntu-18.04_slim` everything is chill.

I actually closed the issue, but should I leave it open? the issue is technicaly still there.

**Comment by ChristophSchranz** [comment]
Can you investigate which image is used if you pull the latest verstion? Does this also happen to you, if you tag this version?

**Comment by SamueLacombe** [comment]
Hello, here is the info:

**Comment by SamueLacombe** [comment]
Hello here is the info: (and yes its also happen if I tag)

"Id": "sha256:a148d3279e49e8a908359116a35539d07d985a667b6174d9588fe40d04ff60d8",

  "RepoTags": ["cschranz/gpu-jupyter:latest"],

  "RepoDigests": ["cschranz/gpu-jupyter@sha256:4e58b6d8cb40282977df41433c2d14f4b1236599dfd9a63e0f318768eb1e8841"]
