### ISSUE TITLE
GPU Mem usage 

### ISSUE THREAD

**Issue by choff5507** [iot-salzburg/gpu-jupyter#79]
Im curious if anyone has noticed this behavior. 

For some reason when I have a notebook open for some time the memory usage on my GPU will max out. Stopping and restarting the docker container will clear it back to the normal level. It's happened previously that it would max out and could not allocate more memory for training. 

I am working on a very small dataset so there's no way it's related to the work at hand but it appears there is something happening in the background. 

Anyone have any suggestions or ideas?

**Comment by ChristophSchranz** [comment]
Sorry for the late response. 
This could be an error that was fixed in CUDA's more recent images. Please reopen if it occurs also in images based on `nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04` or later.
