### ISSUE TITLE
Support for AMD GPUs

### ISSUE THREAD

**Issue by Jille** [iot-salzburg/gpu-jupyter#83]
Hey,

Any plans to support AMD GPUs?

**Comment by ChristophSchranz** [comment]
Hey,
to support AMD GPUs, docker has to offer the possibility to use them inside containers. Then it should be possible to replace the src/Dockerfile.header with an AMD-compatible base image and use GPU-libraries for AMD. 
I don't know if there are any base images for AMD GPUs, so there are no plans to support them at the moment.

In case you know if this is possible, please reopen this issue and create a merge request if you like!
