### ISSUE TITLE
Trying to build with ROCM backend 

### ISSUE THREAD

**Issue by nfrik** [iot-salzburg/gpu-jupyter#84]
Any ideas how to build an image for AMD ROCM? I and replaced the base image with a compatible ROCM Pytorch alternative:

```
rocm/pytorch:rocm5.2.3_ubuntu20.04_py3.7_pytorch_1.12.1
```

But I get an error trying to run useradd command:

```
useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}"
```

```
useradd: UID 1000 is not unique
The command '/bin/bash -o pipefail -c useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}"' returned a non-zero code: 4
```

**Comment by ChristophSchranz** [comment]
Hi @nfrik ,
I'm sorry that I can't help you, as you pull an image from `rocm` which I don't know and which is out of scope for this image that is pulled from nvidia. Hopefully you can debug it when you run `docker exec -it [UID] bash` and then run the struggling lines manually.
