### ISSUE TITLE
running on windows from powershell.

### ISSUE THREAD

**Issue by PGTBoos** [iot-salzburg/gpu-jupyter#85]
i've changed the small script to be compliant with powershell  () => {} and echo
~~~
git clone https://github.com/iot-salzburg/gpu-jupyter.git
cd gpu-jupyter

echo # Check for available supported CUDA versions
git branch  

echo # select the desired (CUDA)-version
git checkout v1.4_cuda-11.6_ubuntu-20.04  

echo # generate a Dockerfile with python and without Julia and R
echo # generate the Dockerfile with only a python interpreter (see options: ./generate-Dockerfile.sh --help)
./generate-Dockerfile.sh --python-only  

echo  # will take a while
docker build -t gpu-jupyter .build/ 
docker run --gpus all -d -it -p 8848:8888 -v ${pwd}/data:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" --user root --restart always --name gpu-jupyter_1 gpu-jupyter
~~~

this resulted in the creation of the image however, quite a lot of errors as well.

------
 > [ 7/41] RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su &&     sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers &&     sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers &&     useradd -l -m -s /bin/bash -N -u "1000" "jovyan" &&     mkdir -p "/opt/conda" &&     chown "jovyan:100" "/opt/conda" &&     chmod g+w /etc/passwd &&     fix-permissions "/home/jovyan" &&     fix-permissions "/opt/conda":
#11 0.542 /bin/bash: /usr/local/bin/fix-permissions: /bin/bash^M: bad interpreter: No such file or directory
------
executor failed running [/bin/bash -o pipefail -c echo "auth requisite pam_deny.so" >> /etc/pam.d/su &&     sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers &&     sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers &&     useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}" &&     mkdir -p "${CONDA_DIR}" &&     chown "${NB_USER}:${NB_GID}" "${CONDA_DIR}" &&     chmod g+w /etc/passwd &&     fix-permissions "${HOME}" &&     fix-permissions "${CONDA_DIR}"]: exit code: 126

`C:\Docker\gpu-jupyter>docker run --gpus all -d -it -p 8848:8888 -v ${pwd}/data:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" --user root --restart always --name gpu-jupyter_1 gpu-jupyter`
Unable to find image 'gpu-jupyter:latest' locally
docker: Error response from daemon: pull access denied for gpu-jupyter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

--
maybe someone knows the issu, or have some advice here.

**Comment by mathematicalmichael** [comment]
I'm not sure the image actually built successfully, as the last error is classic "docker could not find your image"
I'm not familiar with powershell, but the error at `7/41` doesn't quite make sense to me ... `bash` should be available in the image.

**Comment by ChristophSchranz** [comment]
I agree with the points of @mathematicalmichael 

In order to debug, what is the output if you pull the image without locally building it?
`docker run --gpus all -d -it -p 8848:8888 -v $(pwd)/data:/home/jovyan/work -e GRANT_SUDO=yes -e JUPYTER_ENABLE_LAB=yes --user root cschranz/gpu-jupyter:v1.4_cuda-11.6_ubuntu-20.04_python-only`

And it wonders me that the Error says that the pull access is denied. Maybe there is a docker setting that urges you to log in. Can you test this too?
