### ISSUE TITLE
Let user change its own password

### ISSUE THREAD

**Issue by mr-falken** [iot-salzburg/gpu-jupyter#90]
Hi!
We're deploying this notebook as a service in our paas environment and a very important feature would be letting the end user set its own password after first login (with provided token), without our intervention or without our infrastructure team knowing the password.

For what I read [here](https://github.com/iot-salzburg/gpu-jupyter/issues/54) and [here](https://github.com/iot-salzburg/gpu-jupyter/issues/56) all suggested solutions involve rebuilding / restarting the container from our side: is that correct ?
No other workaround ?

Thanks!

**Comment by mathematicalmichael** [comment]
hmmm. not particularly. I think in your situation you may be better suited with a jupyterhub + oauth deployment (like, integrate it with github identity). I use these containers in such an environment myself.
