### ISSUE TITLE
Could someone assist with getting this container working

### ISSUE THREAD

**Issue by choff5507** [iot-salzburg/gpu-jupyter#91]
So, as far as I can tell I followed the directions listed in the README. I am running Ubuntu and tried driver version 525 to begin with which was on CUDA 12. I also tried 515 which was CUDA 11.7 and in both instances I got the following error:

`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

In both cases I can run nvidia-smi perfectly fine from my command line so I can see the card and the other details. According to the docs having a newer version of CUDA on the host machine is fine. So, Im curious if someone can give me a tip on what I should do to continue to troubleshoot. Id really like to get this working. 

Thank you

**Comment by ukd1** [comment]
@choff5507 did you solve this?
