### ISSUE TITLE
Couldn't invoke ptxas

### ISSUE THREAD

**Issue by int-rnd** [iot-salzburg/gpu-jupyter#93]
First thanks for all your wonderful work!

I am using gpu-jupyter with the version tagged as v1.4_cuda-11.6_ubuntu-20.04

Everything works great until I try to fit models. I get an error saying it cannot find ptxas. Looking at the filesystem, I cannot find ptxas anywhere in teh container filesystem. Searching online I found a discussion where they had a similar issue due to an upstream image removing the binary. (https://github.com/google/jax/discussions/6843) It seems like the same thing may have happened here. 

To fix it after the fact, I have found that running 

`sudo /opt/conda/bin/conda install -c nvidia cuda-nvcc -y`

followed by making a symbolic link so it can found by the ipython kernel

`sudo ln -s /opt/conda/bin/ptxas /usr/bin/ptxas`

I figured I would post this here in the hopes that there is a more elegant/permanent fix.

Let me know what other detail you need.

**Comment by ChristophSchranz** [comment]
Hi @int-rnd 

I've tried to reproduced your result, but got a different error as the internals of jax might have changed. It says the GPU can't be found although it is detected by, e.g., torch:
`No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)`

After setting your suggested workaround it worked, which means this might be needed to update.
```
sudo /opt/conda/bin/conda install -c nvidia cuda-nvcc -y
sudo ln -s /opt/conda/bin/ptxas /usr/bin/ptxas
```
Therefore I will fix this in the next commits.
