### ISSUE TITLE
nvtop src directory

### ISSUE THREAD

**Issue by ChristofKaufmann** [iot-salzburg/gpu-jupyter#94]
I seems, after building and installing nvtop you are removing the wrong (non-existing) directory. In line 32 and 33 you clone and go into `/run/nvtop`, but in line 37 you remove `/tmp/nvtop`.
https://github.com/iot-salzburg/gpu-jupyter/blob/117d88e74b361659d8feac9264f081e60847549b/src/Dockerfile.gpulibs#L32-L37
When I look inside the image, I can see the source and build artifacts in `/run/nvtop/`.

**Comment by ChristophSchranz** [comment]
Yes @ChristofKaufmann you are right! Thank you!
